image: golang:latest
script:
  - go get -u github.com/kardianos/govendor
  - cd /go
  - mkdir -p src/github.com/boyvanduuren/
  - ln -s /var/run/octorunner /go/src/github.com/boyvanduuren/octorunner
  - cd /go/src/github.com/boyvanduuren/octorunner
  - govendor sync
  - go get
  - go test ./...
