image: golang:latest
script:
  - curl https://glide.sh/get | sh
  - cd /go
  - mkdir -p src/github.com/boyvanduuren/
  - ln -s /var/run/octorunner /go/src/github.com/boyvanduuren/octorunner
  - cd /go/src/github.com/boyvanduuren/octorunner
  - glide install --strip-vendor
  - go get
  - go test $(glide novendor)
