// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/boyvanduuren/octorunner/lib/webapi/design
// --out=$(GOPATH)\src\github.com\boyvanduuren\octorunner\lib\webapi
// --version=v1.1.0-dirty
//
// API "octorunner": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// JobHref returns the resource href.
func JobHref(jobID interface{}) string {
	paramjobID := strings.TrimLeftFunc(fmt.Sprintf("%v", jobID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/jobs/%v", paramjobID)
}

// ProjectHref returns the resource href.
func ProjectHref(projectID interface{}) string {
	paramprojectID := strings.TrimLeftFunc(fmt.Sprintf("%v", projectID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/projects/%v", paramprojectID)
}
